[project]
name = "sistema-de-comandas"
version = "0.1.0"
description = "Sistema de gerenciamento de comandas utilizando FastAPI, MongoDB e MinIO."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "beanie==1.26.0",
    "faker>=40.15.0",
    "fastapi>=0.136.1",
    "fastapi-pagination>=0.15.12",
    "httpx>=0.28.1",
    "minio>=7.2.20",
    "motor>=3.7.1",
    "pydantic-settings>=2.14.1",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.28",
    "rich>=14.0.0",
    "uvicorn>=0.46.0",
]
