"""upgrades

Revision ID: d8a39d948f7b
Revises: c3e2c7476d4c
Create Date: 2026-05-17 20:49:42.108544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd8a39d948f7b'
down_revision: Union[str, None] = 'c3e2c7476d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commands', 'status',
               existing_type=postgresql.ENUM('ABERTA', 'FECHADA', 'CANCELADA', name='commandstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('payments', 'method',
               existing_type=postgresql.ENUM('DINHEIRO', 'CARTAO', 'PIX', name='paymentmethod'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDENTE', 'PAGO', 'ESTORNADO', name='paymentstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.add_column('products', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('products', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))
    op.add_column('products', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('products', 'ativo')
    op.drop_column('products', 'categoria')
    op.drop_column('products', 'nome')
    op.drop_column('products', 'descricao')
    op.drop_column('products', 'preco')
    op.alter_column('tables', 'status',
               existing_type=postgresql.ENUM('LIVRE', 'OCUPADA', name='tablestatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('LIVRE', 'OCUPADA', name='tablestatus'),
               existing_nullable=False)
    op.add_column('products', sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('descricao', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('categoria', postgresql.ENUM('BEBIDA', 'PRATO_PRINCIPAL', 'ENTRADA', 'SOBREMESA', 'LANCHE', 'OUTRO', name='categoriaenum'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('products', 'active')
    op.drop_column('products', 'price')
    op.drop_column('products', 'category')
    op.drop_column('products', 'description')
    op.drop_column('products', 'name')
    op.alter_column('payments', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('PENDENTE', 'PAGO', 'ESTORNADO', name='paymentstatus'),
               existing_nullable=False)
    op.alter_column('payments', 'method',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('DINHEIRO', 'CARTAO', 'PIX', name='paymentmethod'),
               existing_nullable=False)
    op.alter_column('commands', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('ABERTA', 'FECHADA', 'CANCELADA', name='commandstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
